export const INITIALIZE = 'explorer/INITIALIZE'
export const UNSET = 'explorer/UNSET'

// Operations
export const CLEAR_OPERATIONS = 'explorer/CLEAR_OPERATIONS'
export const LAST_OPERATIONS_FETCH = 'explorer/LAST_OPERATIONS_FETCH'
export const LAST_OPERATIONS_FETCH_SUCCESS = 'explorer/LAST_OPERATIONS_FETCH_SUCCESS'
export const LAST_OPERATIONS_FETCH_FAILURE = 'explorer/LAST_OPERATIONS_FETCH_FAILURE'

// Header Info
export const HEADER_FETCH = 'explorer/HEADER_FETCH'
export const HEADER_FETCH_SUCCESS = 'explorer/HEADER_FETCH_SUCCESS'
export const HEADER_FETCH_FAILURE = 'explorer/HEADER_FETCH_FAILURE'

// Last Block
export const LAST_BLOCK_NUMBER_FETCH = 'explorer/LAST_BLOCK_NUMBER_FETCH'
export const LAST_BLOCK_NUMBER_FETCH_SUCCESS = 'explorer/LAST_BLOCK_NUMBER_FETCH_SUCCESS'
export const LAST_BLOCK_NUMBER_FETCH_FAILURE = 'explorer/LAST_BLOCK_NUMBER_FETCH_FAILURE'

// Lookup Assets
export const LOOKUP_ASSETS_FETCH = 'explorer/LOOKUP_ASSETS_FETCH'
export const LOOKUP_ASSETS_FETCH_SUCCESS = 'explorer/LOOKUP_ASSETS_FETCH_SUCCESS'
export const LOOKUP_ASSETS_FETCH_FAILURE = 'explorer/LOOKUP_ASSETS_FETCH_FAILURE'

// Lookup Assets
export const LOOKUP_ACCOUNTS_FETCH = 'explorer/LOOKUP_ACCOUNTS_FETCH'
export const LOOKUP_ACCOUNTS_FETCH_SUCCESS = 'explorer/LOOKUP_ACCOUNTS_FETCH_SUCCESS'
export const LOOKUP_ACCOUNTS_FETCH_FAILURE = 'explorer/LOOKUP_ACCOUNTS_FETCH_FAILURE'


