export const INITIALIZE = 'explorer/INITIALIZE'
export const UNSET = 'explorer/UNSET'

export const LAST_OPERATIONS_FETCH = 'explorer/LAST_OPERATIONS_FETCH'
export const LAST_OPERATIONS_FETCH_SUCCESS = 'explorer/LAST_OPERATIONS_FETCH_SUCCESS'
export const LAST_OPERATIONS_FETCH_FAILURE = 'explorer/LAST_OPERATIONS_FETCH_FAILURE'
