export const AccountActionTypes = {
  FETCH_ACCOUNTS: '[ACCOUNT] FETCH_ACCOUNTS',
  FETCH_ACCOUNTS_SUCCESS: '[ACCOUNT] FETCH_ACCOUNTS_SUCCESS',
  FETCH_ACCOUNTS_FAILURE: '[ACCOUNT] FETCH_ACCOUNTS_FAILURE',
};
