const AccountActionTypes = {
  FETCH_ACCOUNTS: '[ACCOUNTS] FETCH_ACCOUNTS',
  FETCH_ACCOUNTS_SUCCESS: '[ACCOUNTS] FETCH_ACCOUNTS_SUCCESS',
  FETCH_ACCOUNTS_FAILURE: '[ACCOUNTS] FETCH_ACCOUNTS_FAILURE',
  SET_IS_FETCHING_ACCOUNTS: `[ACCOUNTS] SET_IS_FETCHING_ACCOUNTS`,
};

export default AccountActionTypes;
