const AccountActionTypes = {
  FETCH_ACCOUNTS: '[ACCOUNTS] FETCH_ACCOUNTS',
  FETCH_ACCOUNTS_SUCCESS: '[ACCOUNTS] FETCH_ACCOUNTS_SUCCESS',
  FETCH_ACCOUNTS_FAILURE: '[ACCOUNTS] FETCH_ACCOUNTS_FAILURE',
  FETCH_ACCOUNTS_LOADING: `[ACCOUNTS] FETCH_ACCOUNTS_LOADING`,
};

export default AccountActionTypes;
