export const ActionTypes = {
  FETCH_TRANSACTIONS: 'FETCH_TRANSACTIONS',
  FETCH_TRANSACTIONS_REQUEST: 'FETCH_TRANSACTIONS_REQUEST',
  FETCH_TRANSACTIONS_REQUEST_SUCCEEDED: 'FETCH_TRANSACTIONS_REQUEST_SUCCEEDED',
  FETCH_TRANSACTIONS_REQUEST_FAILED: 'FETCH_TRANSACTIONS_REQUEST_FAILED',
};
